DEFAULT_INITIAL_DELAY_SECONDS = 5.0
DEFAULT_CHARACTER_INTERVAL_SECONDS = 0.05
COUNTDOWN_STEP_SECONDS = 1.0

MIN_INITIAL_DELAY_SECONDS = 1.0
MIN_CHARACTER_INTERVAL_SECONDS = 0.0
MAX_CHARACTER_INTERVAL_SECONDS = 5.0

